export const tracks = [
    { name: "Ain't No Sunshine - Bill Withers", durationMs: 125000 },
    { name: "Ain't No Mountain High Enough - Marvin Gaye, Tammi Terrell", durationMs: 152000 },
    { name: "When a Man Loves a Woman - Percy Sledge", durationMs: 174000 },
    { name: "Volare (Nel Blu di Pinto di Blu) - Gipsy Kings", durationMs: 219000 },
    { name: "Mambo Italiano - Dean Martin", durationMs: 143000 },
    { name: "Rhythm Divine - Enrique Iglesias", durationMs: 210000 },
    { name: "Baby, I Love Your Way - Big Mountain", durationMs: 250000 },
    { name: "Feel - Robbie Williams", durationMs: 264000 },
    { name: "Hold Tight - Change", durationMs: 269000 },
    { name: "Celebration - Kool & The Gang", durationMs: 299000 },
    { name: "I've Been Thinking About You - Londonbeat", durationMs: 230000 },
    { name: "Pump Up The Jam - Technotronic", durationMs: 215000 },
    { name: "What's Love Got to Do with It - Tina Turner", durationMs: 230000 },
    { name: "All Night Long (All Night) - Lionel Richie", durationMs: 259000 },
    { name: "You're My Heart, You're My Soul '98 - Modern Talking", durationMs: 230000 },
    { name: "Part-Time Lover - Stevie Wonder", durationMs: 253000 },
    { name: "Across the Lines - Tracy Chapman", durationMs: 205000 },
    { name: "Dream On - Aerosmith", durationMs: 268000 },
    { name: "Self Control - Laura Branigan", durationMs: 246000 },
    { name: "Get Down On It - Kool & The Gang", durationMs: 212000 },
    { name: "Hold the Line - Toto", durationMs: 236000 },
    { name: "Layla - Derek & The Dominos", durationMs: 424000 },
    { name: "Time After Time - Cyndi Lauper", durationMs: 241000 },
    { name: "Africa - Toto", durationMs: 296000 },
    { name: "You Can't Hurry Love - Phil Collins", durationMs: 176000 },
    { name: "Inspiration - Gipsy Kings", durationMs: 221000 },
    { name: "It's My Life - Bon Jovi", durationMs: 224000 },
    { name: "It's Raining Men - The Weather Girls", durationMs: 215000 },
    { name: "Build Me Up Buttercup - The Foundations", durationMs: 178000 },
    { name: "Fields Of Gold - Sting", durationMs: 222000 }
]
